baseURL = "https://dawitanelay.dev/"
languageCode = "en-us"
title = "Dawit Anelay"
theme = "hugo-theme-papermod"
publishDir = "public"
enableGitInfo = true

[params]
  author = "Dawit Anelay"
  description = "DevOps, coding, and musings."
